services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["sh", "-c", "npm run hello && npm run import && npm run analyse"]

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
